### ISSUE TITLE
Code is missing a license

### ISSUE THREAD

**Issue by desplesda** [UnityTechnologies/PlaygroundProject#1]
Thanks so much for publishing the code for this! Can you please add a license to the repo? Without one, the ability of others to use this code is limited.

**Comment by ciro-unity** [comment]
Yes, sure! The repository wasn't originally meant to be shared, that's why it was missing. I chose the MIT license.

**Comment by desplesda** [comment]
Thank you! :) And thanks again for making this awesome project!
