### ISSUE TITLE
Error Picking Coin on RogueLike

### ISSUE THREAD

**Issue by romifauzi** [UnityTechnologies/PlaygroundProject#12]
Hi,

I've found an error when trying the roguelike scene, when the player tries to pick up the coin, it gaves this error:

MissingReferenceException: The variable resourceItemPrefab of UIScript doesn't exist anymore.
You probably need to reassign the resourceItemPrefab variable of the 'UIScript' script in the inspector.
UnityEngine.Object.Instantiate[GameObject] (UnityEngine.GameObject original) (at C:/buildslave/unity/build/Runtime/Export/UnityEngineObject.cs:201)
UIScript.AddResource (System.String resourceType, Int32 pickedUpAmount, UnityEngine.Sprite graphics) (at Assets/Scripts/_DONT_USE_/User Interface/UIScript.cs:135)
ResourceAttribute.OnTriggerEnter2D (UnityEngine.Collider2D otherCollider) (at Assets/Scripts/Attributes/ResourceAttribute.cs:33)

and under the UIScript, we can't assign the resourceItemPrefabs, since its hidden by the editor script, how do we fix this?

Thanks

**Comment by ciro-unity** [comment]
Hey @romifauzi, thanks for putting the issue in. I will take a look at this as soon as I can!

**Comment by booyaa** [comment]
I think this has been resolved, can't reproduce with the Jan18 build of the package. [download link](https://connect.unity.com/p/unity-playground)

**Comment by ciro-unity** [comment]
Thanks @booyaa, yes it should be resolved :)
