### ISSUE TITLE
Importing PP as a Project doesn't provide menu options to turn on/off Playground

### ISSUE THREAD

**Issue by JimboPicton** [UnityTechnologies/PlaygroundProject#14]
When importing the current build of the project from GutHub, the only option available under 'Playground' in file menu is 'Export Unity Package' - options to turn on/off Playground Project are not available (although these are demonstrated when the current Global Game Jam Installer Package is used). (Using Unity 2017.3.f1 Personal edn)

**Comment by JimboPicton** [comment]
Resolved after discussion with Ciro using the 'Asset-Store' fork (will be rolled into a future PP Master build).

**Comment by Janhan** [comment]
Using the move scipt I got the Message "RigidbodyType2D' does not exist in the current context"

How could I solve the error

Thanks
