### ISSUE TITLE
Unity Crash 

### ISSUE THREAD

**Issue by shohan4556** [UnityTechnologies/PlaygroundProject#2]
Each time I try to open a Scene Unity crashed I am using unity 5.3.5

**Comment by ciro-unity** [comment]
Hey shohan, unfortunately I have authored the project with the 5.4 series, so you will need to open it with a 5.4 or later version.

Usually you would be able to open such a simple project with older versions, but in this case it seems like something critical changed between 5.3 and 5.4 in regards to prefabs.
