### ISSUE TITLE
TakeBall Action

### ISSUE THREAD

**Issue by Lone-Coder** [UnityTechnologies/PlaygroundProject#3]
My kids tried to make a quiddich game. Here's a quick action that I coded up for it.

```
using UnityEngine;
using System.Collections;

public class TakeBall : Action {

    public override bool ExecuteAction(GameObject other)
    {
        other.transform.SetParent(transform);
        other.GetComponent<Rigidbody2D>().isKinematic = true;

        return base.ExecuteAction(other);
    }
}

```

**Comment by ciro-unity** [comment]
Yeah, I've been thinking of a way to pick up an object and carry it around. But how would you release it? Maybe on collision?

**Comment by Lone-Coder** [comment]
If an enemy player knocked into the ball they would steal it. Or it would get destroyed at the goal.

Should probably be called AttachChild or something. And should check for the existence of the rigidbody.

**Comment by ciro-unity** [comment]
_AttachChild_ seems like a very technical name for kids who have never done game development. _AttachObject_ is already better.

I'm also wondering if it could be made into one Action class to both pick up and release objects (and decide what it does by using a flag or a enum) for the sake of ease in maintaining the code. Or would it be better to have 2 separate Actions? 🤔 

This project poses so many _moral doubts_!

**Comment by Lone-Coder** [comment]
Maybe just name it Attach.

I'd keep it simple and make two actions.
