### ISSUE TITLE
AutoMoveTowardsPlayer would be better as AutoMoveTowardsTag

### ISSUE THREAD

**Issue by Lone-Coder** [UnityTechnologies/PlaygroundProject#4]
In the quiddich game we often needed an enemy to move towards a ball instead of just the player, so please don't limit AutoMoveTowardsPlayer to only work with players.

**Comment by Lone-Coder** [comment]
It'd also be nice if it could target more than one tag, for instance Player, Snitch, and Quaffle could be set and an enemy should seek the closest.

**Comment by ciro-unity** [comment]
I like the idea, however I have to think about how to do it while keeping things clean. I'm thinking of edge cases: what if the users want to tag both players? (as in, any of the 2 players, whoever is nearer)

Don't forget one of the ideas of this whole framework is to leave the kids the possibility to modify the code... if I make it too tangled, then that becomes impossible!

**Comment by Lone-Coder** [comment]
If you're wanting to have kids get into the code, I'd avoid the whole
system of "visual programming" style of condition and action behaviors.
It's bad coding in my opinion. Just make the actions each a method and have
them code the conditions. They need practice writing real if statements.
